//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalVet.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortalVet.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; align=&quot;center&quot; width=&quot;100%&quot; style=&quot;background-color:#F9F9F9;border:0;border-collapse:collapse;border-spacing:0;margin:0 auto;max-width:100%;width:100%;&quot;&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td align=&quot;center&quot;&gt;
        ///                &lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; align=&quot;center&quot; class=&quot;table-700&quot; style=&quot;background-color:#FFFFFF;border:0;border-collapse:collapse;border-spacing:0;margin:0 auto;max-width:700px;width:700px;&quot;&gt;
        ///                    &lt;tbody&gt;
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BemVindoCredenciais {
            get {
                return ResourceManager.GetString("BemVindoCredenciais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot; xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;!--[if (gte mso 9)|(IE)]&gt;
        ///    &lt;xml&gt;
        ///        &lt;o:OfficeDocumentSettings&gt;
        ///            &lt;o:AllowPNG/&gt;
        ///            &lt;o:PixelsPerInch&gt;96&lt;/o:PixelsPerInch&gt;
        ///        &lt;/o:OfficeDocumentSettings&gt;
        ///    &lt;/xml&gt;
        ///    &lt;![endif]--&gt;
        ///    &lt;meta na [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MasterNovo {
            get {
                return ResourceManager.GetString("MasterNovo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; align=&quot;center&quot; width=&quot;100%&quot; style=&quot;background-color:#F9F9F9;border:0;border-collapse:collapse;border-spacing:0;margin:0 auto;max-width:100%;width:100%;&quot;&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td align=&quot;center&quot;&gt;
        ///                &lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; align=&quot;center&quot; class=&quot;table-700&quot; style=&quot;background-color:#FFFFFF;border:0;border-collapse:collapse;border-spacing:0;margin:0 auto;max-width:700px;width:700px;&quot;&gt;
        ///                    &lt;tbody&gt;
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MensagemModelo {
            get {
                return ResourceManager.GetString("MensagemModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; align=&quot;center&quot; width=&quot;100%&quot; style=&quot;background-color:#F9F9F9;border:0;border-collapse:collapse;border-spacing:0;margin:0 auto;max-width:100%;width:100%;&quot;&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td align=&quot;center&quot;&gt;
        ///                &lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; align=&quot;center&quot; class=&quot;table-700&quot; style=&quot;background-color:#FFFFFF;border:0;border-collapse:collapse;border-spacing:0;margin:0 auto;max-width:700px;width:700px;&quot;&gt;
        ///                    &lt;tbody&gt;
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MensagemModeloBotao {
            get {
                return ResourceManager.GetString("MensagemModeloBotao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; align=&quot;center&quot; width=&quot;100%&quot; style=&quot;background-color:#F9F9F9;border:0;border-collapse:collapse;border-spacing:0;margin:0 auto;max-width:100%;width:100%;&quot;&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td align=&quot;center&quot;&gt;
        ///                &lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; align=&quot;center&quot; class=&quot;table-700&quot; style=&quot;background-color:#FFFFFF;border:0;border-collapse:collapse;border-spacing:0;margin:0 auto;max-width:700px;width:700px;&quot;&gt;
        ///                    &lt;tbody&gt;
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NotificacaoExame {
            get {
                return ResourceManager.GetString("NotificacaoExame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; align=&quot;center&quot; width=&quot;100%&quot; style=&quot;background-color:#F9F9F9;border:0;border-collapse:collapse;border-spacing:0;margin:0 auto;max-width:100%;width:100%;&quot;&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td align=&quot;center&quot;&gt;
        ///                &lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; align=&quot;center&quot; class=&quot;table-700&quot; style=&quot;background-color:#FFFFFF;border:0;border-collapse:collapse;border-spacing:0;margin:0 auto;max-width:700px;width:700px;&quot;&gt;
        ///                    &lt;tbody&gt;
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NovaSenha {
            get {
                return ResourceManager.GetString("NovaSenha", resourceCulture);
            }
        }
    }
}
